# Generated by Django 4.2.2 on 2023-06-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=200)),
                ("bot_user_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=200)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="bender.bot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=3)),
                ("text", models.TextField()),
                ("user_id", models.CharField(max_length=50, unique=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bender.community",
                    ),
                ),
            ],
        ),
    ]
