# Generated by Django 4.2.2 on 2023-06-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prey",
            name="type",
            field=models.CharField(
                choices=[("prog", "Program"), ("my", "My"), ("com", "Community")],
                default="prog",
                max_length=4,
            ),
        ),
    ]
