# Generated by Django 4.2.2 on 2023-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bender", "0003_alter_bot_bot_user_id_alter_prey_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="bot_user_id",
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
