# Generated by Django 4.2.2 on 2023-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bender", "0004_alter_bot_bot_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="prey",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
